# Generated by Django 4.2.2 on 2023-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_lorem', models.TextField()),
                ('about_name', models.CharField(max_length=2000)),
                ('about_manzil', models.CharField(max_length=2000)),
                ('about_call', models.IntegerField()),
                ('about_email', models.CharField(max_length=2000)),
                ('about_video', models.FileField(upload_to='video')),
                ('about_clent', models.IntegerField()),
                ('about_projects', models.IntegerField()),
                ('about_practice', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
            options={
                'verbose_name': 'Carusel',
                'verbose_name_plural': 'Carusel',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('call', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cantact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_hello', models.CharField(max_length=200)),
                ('home_lorem', models.TextField()),
                ('home_video', models.FileField(upload_to='video')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='jpg')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icon',
            },
        ),
    ]
